baseURL = 'https://the-ccc.github.io/'
languageCode = 'en-us'
title = 'Coding Conundrums Community'
theme = 'paper'
[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'the-ccc'                 # github.com/YOUR_GITHUB_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = 'https://fedia.social/@zstg'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)